# Generated by Django 4.0.6 on 2023-09-09 21:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombres')),
                ('ip_address', models.CharField(max_length=15, unique=True, verbose_name='IP')),
                ('home_address', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Telefono')),
                ('month_payment', models.CharField(default='0', max_length=10, verbose_name='Pago mensual')),
                ('mbps', models.CharField(default='0', max_length=10, verbose_name='Mbps')),
                ('install_date', models.DateField(verbose_name='Fecha de instalación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.SmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=8, verbose_name='Mes')),
                ('year', models.CharField(default='2023', max_length=10, verbose_name='Año')),
                ('amount', models.CharField(blank=True, default='auto', max_length=10, verbose_name='Monto')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha de pago')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['year', 'month'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=20, verbose_name='Acción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historial',
            },
        ),
    ]
