# Generated by Django 4.0.6 on 2022-07-05 22:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.SmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=6, verbose_name='Mes'),
        ),
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('month', models.SmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=6, verbose_name='Mes')),
                ('year', models.CharField(default='2022', max_length=10, verbose_name='Año')),
                ('amount', models.CharField(default=50, max_length=10, verbose_name='Monto')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha de pago')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.customer', verbose_name='Cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Pago',
                'verbose_name_plural': 'historical Pagos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHistory',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('action', models.CharField(max_length=20, verbose_name='Acción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.customer', verbose_name='Cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Historial',
                'verbose_name_plural': 'historical Historial',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Nombres')),
                ('ip_address', models.CharField(db_index=True, max_length=15, verbose_name='IP')),
                ('home_address', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Telefono')),
                ('month_payment', models.CharField(default='0', max_length=10, verbose_name='Pago mensual')),
                ('mbps', models.CharField(default='0', max_length=10, verbose_name='Mbps')),
                ('install_date', models.DateField(verbose_name='Fecha de instalación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'verbose_name_plural': 'historical Clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
