# Generated by Django 4.0.6 on 2023-08-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_payment_date_alter_payment_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['year', 'month'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='amount',
            field=models.CharField(blank=True, default='auto', max_length=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='month',
            field=models.SmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=7, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='year',
            field=models.CharField(default='2023', max_length=10, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(blank=True, default='auto', max_length=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.SmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=7, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.CharField(default='2023', max_length=10, verbose_name='Año'),
        ),
    ]
