# Generated by Django 4.0.6 on 2023-09-09 21:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('income', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ingreso')),
                ('expense', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Egreso')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Caja')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Cuenta Total',
                'verbose_name_plural': 'Cuenta Total',
            },
        ),
        migrations.CreateModel(
            name='AccountItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pago')),
                ('type', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], default='ingreso', max_length=10, verbose_name='Ingreso / Egreso')),
                ('details', models.CharField(default='', max_length=50, verbose_name='Detalles')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Ingreso Egreso',
                'verbose_name_plural': 'Ingresos Egresos',
            },
        ),
    ]
