# Generated by Django 4.0.6 on 2023-08-09 15:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], decimal_places=2, max_digits=6, verbose_name='Pago')),
                ('type', models.CharField(default='ingreso', max_length=10, verbose_name='Ingreso / Egreso')),
                ('details', models.CharField(default='', max_length=50, verbose_name='Detalles')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('amount', models.DecimalField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], decimal_places=2, max_digits=6, verbose_name='Pago')),
                ('type', models.CharField(default='ingreso', max_length=10, verbose_name='Ingreso / Egreso')),
                ('details', models.CharField(default='', max_length=50, verbose_name='Detalles')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cuenta',
                'verbose_name_plural': 'historical Cuentas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
