# Generated by Django 4.0.6 on 2023-09-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountitem',
            options={'verbose_name': 'Ingreso - Egreso', 'verbose_name_plural': 'Ingresos - Egresos'},
        ),
        migrations.AlterField(
            model_name='account',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Egreso Total'),
        ),
        migrations.AlterField(
            model_name='account',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ingreso Total'),
        ),
        migrations.AlterField(
            model_name='account',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Caja Total'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima actualización'),
        ),
        migrations.AlterField(
            model_name='accountitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='accountitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima actualización'),
        ),
    ]
